nac_job:
    resource: "@NACJobBundle/Resources/config/routing.yml"
    prefix:   /job-platform

nac_netafrica:
    resource: "@NACNetafricaBundle/Resources/config/routing.yml"
    prefix:   /netafrica-consult

nac_prospect:
    resource: "@NACProspectBundle/Resources/config/routing.yml"
    prefix:   /annuaire

# app/config/routing.yml

nac_platform:
    resource: "@NACPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
